class Columns:
    CLIENT = "client"
    SUPPLIER = "supplier"
    TAX = "tax"
    AMOUNT = "amount"
    TAG = "tag"
    HOUR = "hour"
    AMOUNT_RANGE = "amount_range"
    TAG_CHOICES = "tag_choices"
    HOUR_RANGE = "hour_range"